### PR TITLE
Make it work in Internet Explorer

### PR DESCRIPTION
**Pull request by barnslig**
## This is the problem:
The development branch does not work in Internet Explorer. There are visual problems like non-hidden selects and functional problems like non-working multi-selects.

## Steps to reproduce:
Launch the development branch in IE.

## This is my solution:
* [IE does not support multiple-parameter `classList.add()` / `classList.remove()`](https://caniuse.com/#feat=classlist); Replace it with single-parameter calls
+ IE needs polyfills for `Array.prototype.find` / `Array.prototype.includes`; Include them from core-js

### CODE REVIEW

**Comment by barnslig** [comment]
Eventually it makes sense to investigate how to use [`useBuiltIns: 'usage'`](https://babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins) regarding the Polyfills.

**Comment by jshjohnson** [comment]
Which version of IE? Choices only supports >IE11

**Comment by barnslig** [comment]
The problem appears in IE 11 which happens to be the latest version of Internet Explorer.

**Comment by czapkowicz** [comment]
Yeap, on IE11 this lib is pretty much useless.

**Comment by stof** [comment]
instead of bundling polyfills, it might be better to document the polyfills needed for IE 11. This avoids shipping the same polyfills multiple time in a project due to third-party libraries shipping the polyfills by themselves.

**Pull request merged**
