### PR TITLE
Server side filtering

### PR DESCRIPTION
**Pull request by froggiefab**
Hi,

This is a PR for the issue #46.

Not sure if this is what you had in mind though.

I think it might be a good idea to relie on async actions for the Redux/Store object. The dependencies needed would probably make Choices.js bigger though.

### CODE REVIEW

**Comment by jshjohnson** [comment]
Just so I can test this, could you provide a simple Choices config using this functionality please?

Thanks!

**Comment by froggiefab** [comment]
I just pushed a sample in the 'index.html' file.

**Comment by jshjohnson** [comment]
There are a lot of improvements you've made within this pull request that I will be merging in - I have removed (for now) the ability to live search though, as I found it caused race conditions with Redux - I'll look into some async Redux libraries to see if there are any solutions. I have kept the search callback though so there is still the opportunity of handling async actions when a user searches!

Thanks for all your help!

**Comment by froggiefab** [comment]
Thanks a lot !

**Comment by FriOne** [comment]
@jshjohnson Is this in the last version? I want to create wrapper on angular.

**Pull request merged**
