### PR TITLE
Update to Webpack 3

### PR DESCRIPTION
**Pull request by razh**
I rebased #145 on top of master and combined the changes with https://github.com/jshjohnson/Choices/tree/feature/webpack-2.

This adds [`webpack.optimize.ModuleConcatenationPlugin`](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) which results in a smaller bundle size when combined with tree-shaking.

This does reintroduce the unnecessary ES6 bundles, so those could be removed if desired.

| File size | Before | After |
|---|---|---|
| `choices.js` | [186 KB](https://github.com/jshjohnson/Choices/blob/v2.8.7/assets/scripts/dist/choices.js) | [181 KB](https://github.com/razh/Choices/blob/feature/webpack-3-dist/assets/scripts/dist/choices.js)
| `choices.min.js` | [65.4 KB](https://github.com/jshjohnson/Choices/blob/v2.8.7/assets/scripts/dist/choices.min.js) | [58.7 KB](https://github.com/razh/Choices/blob/feature/webpack-3-dist/assets/scripts/dist/choices.min.js) |
| `choices.min.js` (gzip)* | [17.8 KB](https://raw.githubusercontent.com/jshjohnson/Choices/v2.8.7/assets/scripts/dist/choices.min.js) | [16.5 KB](https://raw.githubusercontent.com/razh/Choices/feature/webpack-3-dist/assets/scripts/dist/choices.min.js) |

* I'm using the Network tab in Chrome developer tools as a rough estimate of this.

I've skipped including the build files in this pull request, but I do have a branch with them: https://github.com/razh/Choices/tree/feature/webpack-3-dist

### CODE REVIEW

**Comment by jshjohnson** [comment]
Hey!

Out of interest, if I imported Choices as a module, what version would it import? The transpiled version?

**Comment by razh** [comment]
@jshjohnson Yes, unless I'm mistaken, it would be the transpiled version.

For example, with webpack, it would resolve the `main` field from `package.json`.

https://webpack.js.org/configuration/resolve/#resolve-mainfields

(Travis appears to be failing because of karma-webpack.)

**Comment by jshjohnson** [comment]
I've been planning on swapping Karma/Jasmine with Mocha/Chai for tests which will resolve the issue that is causing Travis to fail (as tests will no longer rely on Webpack). Will update on this soon

**Comment by razh** [comment]
Gotcha, I'll keep this branch rebased and up-to-date.

**Comment by jshjohnson** [comment]
You have a conflict 👍 FYI master is now using mocha + chai so we should only have to deal with one webpack config now

**Comment by razh** [comment]
Judging from the conflicts, I'm going to just close this and create a new PR that omits the ES6 bundles. Thank you for the work that you've done in the meantime, especially with modularizing the codebase!

**Pull request closed without merging**
