### PR TITLE
Feature/select add items

### PR DESCRIPTION
**Pull request by jshjohnson**

### CODE REVIEW

**Comment by curtisblackwell** [comment]
What's preventing you from merging this? I'd love to use Choices, but I need to be able to add options to a select field or provide choices for a text input.

**Comment by jshjohnson** [comment]
This is on hold for the time being - it was initially merged into a release but caused an issue where you couldn't select more than one option on a select input. It needs investigating.

**Comment by curtisblackwell** [comment]
Is that release still tagged? That's what I need it for on this project, so if that's the only issue, it'd work for me for now.

**Comment by jshjohnson** [comment]
@curtisblackwell - https://github.com/jshjohnson/Choices/releases/tag/v2.8.0

**Comment by curtisblackwell** [comment]
Awesome, thank you. I'll give this a go today/Wednesday.

**Comment by dgt41** [comment]
@jshjohnson that means that the v2.8.0 supports addItem again?

**Comment by curtisblackwell** [comment]
@dgt41 Yes. I used 2.8.0 and it was exactly what I needed.

**Comment by dgt41** [comment]
@curtisblackwell thanks for the update! I guess I'll have to reopen [this](https://github.com/joomla/joomla-cms/pull/15916) then 😀

**Comment by jshjohnson** [comment]
Closing this - the codebase has moved on a lot since this was opened causing major conflicts.

**Comment by aarongerig** [comment]
@jshjohnson Do you have an idea/plan (how) to make this possible? I exactly need a combination of both, being able to search for already existing entries, but also adding custom items to a single or multi select field.

Any help is appreciated!

**Pull request closed without merging**
