### PR TITLE
add canUseDom

### PR DESCRIPTION
**Pull request by SampsonCrowley**
added CanUseDom checking so that it doesn't run for SSR

### CODE REVIEW

**Comment by jshjohnson** [comment]
Thanks for this.

Surely there would only need to be conditionals inside the constructors of each class, no? As if they return false, none of their methods will be called? 

Also, the next release will be from `feature/modularise-code`, so would you mind changing he base branch to that instead of master please :)

**Comment by SampsonCrowley** [comment]
I started with just the constructors and still ended up with errors.
Further research is necessary, but this works for the short term and I was
in a hurry to get it up and running

**Comment by SampsonCrowley** [comment]
I'll make a cleaner version from the feature/modularize-code branch later today

**Comment by jshjohnson** [comment]
Closing based on previous comment :)

**Comment by SampsonCrowley** [comment]
sorry for the delay. been really busy. I'll try to get to this by the end of the week

**Pull request closed without merging**
