### PR TITLE
3.x Branch - Adding an item comparer configuration to allow custom comparisons of items.

### PR DESCRIPTION
**Pull request by travist**

### CODE REVIEW

**Comment by jshjohnson** [comment]
The next release will be from develop 👍

**Comment by travist** [comment]
Yes I know. You already committed this in the develop branch and I asked if we could make this against "master" since we would like to include this in a patch release against current stable branch.

**Comment by jshjohnson** [comment]
Ahhh sorry - being an idiot!

**Comment by jshjohnson** [comment]
Thanks 👍

**Pull request merged**
