### PR TITLE
Addressing issue #224

### PR DESCRIPTION
**Pull request by maximmig**
A placeholder is not visible when used together with groups: https://github.com/jshjohnson/Choices/issues/224

### CODE REVIEW

**Comment by jshjohnson** [comment]
Hey - thanks for this. I'm currently doing a [mini-rewrite](https://github.com/jshjohnson/Choices/pull/227) of choices, so would you mind re-opening this pull request but setting the branch to `feature/modularise` instead of master? 

Thanks

**Comment by maximmig** [comment]
There is only `feature/modularise-code` branch, not `feature/modularise`. Did you mean it?

**Comment by maximmig** [comment]
I've changed it and met conflicts, please advise.

**Comment by maximmig** [comment]
It's okay, I've managed to resolve it on my end. I'll close this PR and make a new one.

**Pull request closed without merging**
