### PR TITLE
Enable test on Safari

### PR DESCRIPTION
**Pull request by tinovyatkin**
## Description

Adds missing test on Safari for our suite of visual tests.

## Types of changes

- [x] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tinovyatkin** [comment]
@jshjohnson Please review the new Safari snapshot (GitHub allows to see side-by-side, so, it's handy) - it has some visual changes regarding placeholders, not sure is as supposed to be.

**Comment by jshjohnson** [comment]
I think the comparison is fine but I have noticed since the 'ch' unit PR, that placeholder widths are a lot wider than they need to be:

Screenshot 2019-11-04 at 09 32 03

**Comment by tinovyatkin** [comment]
@jshjohnson Yeah, I know and wrote in original PR (including a link to Chris Mayer writing about it), that `ch` is the width of 0, so, on average it's about 20% wider than normal text. We can tune that in separate PR.
But here I've mostly referred these cases where placeholder disappears at all - I've seen your recent changes to placeholder handling and not sure whether such behavior is desired or it's a regression?

Screenshot 2019-11-04 at 08 14 45

Anyway, I think it's better to merge like this (as it reflects current master state), so then any new changes will come with adjusted snapshots and easier to understand.

**Comment by jshjohnson** [comment]
The placeholder change removed the ability to pass a placeholder via config so that's expected 👍

**Comment by jshjohnson** [comment]
Hey - i'm not sure if it's related to this PR but visual checks seem to behaving strangely in this PR: https://github.com/jshjohnson/Choices/pull/739 which was opened after merging this one

**Comment by tinovyatkin** [comment]
I'm not sure neither, changes here are pretty minimal. I would prefer to wait a day to see if that's a Github Actions problem...

**Pull request merged**
