### PR TITLE
Fetch properties from object

### PR DESCRIPTION
**Pull request by torosegon**

### CODE REVIEW

**Comment by jshjohnson** [comment]
Hey @torosegon, 

Would you be able to give an example of how this works please? Would be good to add an example to the README 👍

**Comment by torosegon** [comment]
Sure. Done.

**Comment by jshjohnson** [comment]
Looks like you've got conflicts. You should be able to just rebase this branch and repush it 👍 Thanks

**Comment by torosegon** [comment]
Hey @jshjohnson this request is up to date.

**Comment by jshjohnson** [comment]
Thanks a lot 👍

**Pull request merged**
