### PR TITLE
Chore: Use GitHub actions

### PR DESCRIPTION
**Pull request by tinovyatkin**
I've see you were trying to adopt GitHub Actions for NPM publishing, but ultimately removed it.
I'm not sure while it was time or some missing feature that prevented use of GitHub Action, but in case it was time/bandwidth I've decided to propose this PR with complete switch for CI / publishing tasks to GitHub Actions (as many popular open source projects already did).

This PR adds 5 actions, 4 of them are result of splitting `.travis.yml` into independent (parallel) actions (it works **3x times** faster than Travis as you may see here) and the last one - is NPM publishing.

Notes for each action:

1. `cypress.yml` - runs Cypress integration tests on every PR. I've also updated `cypress` module to the latest non-breaking version (when you have time you may look why tests breaks starting version 3.3.0). It also may be a good opportunity to setup [Cypress <-> GitHub integration](https://docs.cypress.io/guides/dashboard/projects.html#GitHub-Integration) and adding test recording using repository secrets.
That action should be set as required in [branch protection rules](https://github.com/tinovyatkin/Choices/settings/branches) for this repository.

2. `lint.yml` - runs ESLint with automatic annotations of lint errors to source files in PR. This action runs only when a PR contains any changes to source .js files. You may see how it looks like at [my fork test run](https://github.com/tinovyatkin/Choices/commit/6bd362ce344804e990077a800393a64b2666d804/checks?check_suite_id=273072351). Again, I've used this visit to upgrade ESLint and all plugins, remove `babel-eslint` (it's not needed with latest ESLint version), and also replaced AirBnB config with base version as you don't use React in this project. Also, adjusted ESLint config here to use `overrides` and introduce plugins/env for test files.
[Stylelint](https://github.com/stylelint/stylelint) can be added here if you want later on. 

3. `bundlesize.yml` - do bundles size judging (again, updated `bundesize` to the latest version) and also providing token here to have PR annotations. Runs only when a source Javascript or SCSS file was changed in PR.

4. `unit-test.yml` - runs unit test, with coverage, only when a source Javascript file was changed in PR. Also updated all testing dependencies (`mocha`, `sinon`, `jsdom` and `nyc`) to their latest versions. Also, to unload `package.json` a little, moved all mocha command-line keys to `.mocharc.yml`, so, looks a little prettier now. Added here Codecov coverage reporting, but to make it work you need to [get Codecov token](https://codecov.io/gh/jshjohnson/Choices) and add it to [this repository secrets](https://github.com/jshjohnson/Choices/settings/secrets) as `CODECOV_TOKEN`.

5. `npmpublish.yml` - runs on any push to `master` branch with a tag starting with `v` (a version?). It performs all tests before publishing (I also added `prepublishOnly` script to the `package.json`). To make it work you must add `npm_token` secret (get it from `npm token create` or use your current one `awk -F= '/npmjs.org/ {print $2}' ~/.npmrc`) to [this repository secrets](https://github.com/jshjohnson/Choices/settings/secrets). If you already approved for [GitHub Package Registry](https://github.com/features/package-registry) then it also will publish there.

Another small change is upgrade of `husky` to the latest version, to make it respect [HUSKY_SKIP_INSTALL](https://github.com/typicode/husky/issues/370)

I hope you will find this useful! On merging you can remove `.travis.yml` and stop building there.

### CODE REVIEW

**Comment by jshjohnson** [comment]
hey @tinovyatkin 

Amazing!! Thank you so much 🎉 

The issue I was facing was ensuring the built package was correctly published to NPM. I managed to get publishing working but it was just publishing the changed src files, not the built files. I'm presuming you've managed to get round that?

**Comment by tinovyatkin** [comment]
@jshjohnson yes, that issue is fixed. As far I see from your last attempt you were supposing that `needs: build` will bring build artifacts into publish step, while in fact each step is _clean machine_ (that's why you calling checkout in publishing step). In my version you may see `npm ci` to install deps, and then newly added `prepublishOnly` will do the magic to call `npm run build` before publishing.

If want to add `postversion` script also to automatically push tags to origin after `npm version patch|minor|major`, let me do that...

**Comment by tinovyatkin** [comment]
I replaced bundesize action to not pass our token (it's too powerful, better to create one [as they suggesting](https://github.com/siddharthkp/bundlesize#build-status-for-github) and set it to repository secrets as `BUNDLESIZE_GITHUB_TOKEN`)

Also tuned `preversion` and `postversion` scripts and added `.npmrc`, so, now to publish a new version on NPM (and GitHub Repository) just do `npm version patch|minor|major` from `master` branch on your local machine and it will run all tests, create and tag new version, push everything to GitHub and then GitHub will publish it via action (running test again, however).

**Comment by tinovyatkin** [comment]
@jshjohnson Yes, it's ready. I've tested on [my fork](https://github.com/tinovyatkin/Choices/pull/1). It was _waaay_ more commits, just squashed them before opening this PR 😆, so it looks so easy!

**Comment by jshjohnson** [comment]
Awesome, thanks a lot!

**Comment by tinovyatkin** [comment]
Don't forget to set repository secrets - Codecov and Bundlesizes both have very nice PR decorations and Cypress githut integration can publish screenshots into PR, so, it's easier to review non-JS related PRs likes SCSS, etc.

**Pull request merged**
