### PR TITLE
Feature/select placeholders

### PR DESCRIPTION
**Pull request by jshjohnson**

### CODE REVIEW

**Comment by jshjohnson** [comment]
This feature is close - I have seen an issue when setting a placeholder and then populating choices via `ajax()` though...

**Comment by adammockor** [comment]
Please can you make issue, I can look at it.

**Comment by jshjohnson** [comment]
https://github.com/jshjohnson/Choices/issues/166

**Comment by jshjohnson** [comment]
The ability to have placeholders for single select elements is possible as of [version 3.0.0](https://github.com/jshjohnson/Choices/releases/tag/v3.0.0)

**Pull request closed without merging**
