### PR TITLE
Made IE11 scrollbar check more precise (fixes #621)

### LINKED ISSUE #621: IE11: Dropdown re-opens after selecting item
Happens randomly but frequently. Easy to replicate. Recorded directly from https://joshuajohnson.co.uk/Choices/:

test

Where should we start looking for the cause? Any pointers? Regards,

Sebastian

### PR DESCRIPTION
**Pull request by sebastianhaberey**
Made IE11 scrollbar check more precise (fixes #621)

### CODE REVIEW

**Comment by sebastianhaberey** [comment]
(had to include the CI change to make the tests run)

**Comment by jshjohnson** [comment]
Nice, thanks :)

**Comment by jshjohnson** [comment]
Would you mind incrementing the version please (it should just be a patch)

**Comment by sebastianhaberey** [comment]
I had to improve the algorithm that finds the list item for the fix to work in all possible setups (namely item content without classes. Will increment the version now.

**Comment by sebastianhaberey** [comment]
Done.

**Comment by sebastianhaberey** [comment]
@jshjohnson any chance of a relase? We'd like to integrate this into our product, if possible...

**Comment by mpodorov** [comment]
Please create the new release with this fix.

**Comment by jshjohnson** [comment]
There are conflicts

**Comment by mpodorov** [comment]
@sebastianhaberey Could you remove the changes in .travis.yml file?

**Comment by sebastianhaberey** [comment]
@jshjohnson  @mpodorov apparently there were quite a few changes in the master branch since I opened this request in August. Naturally, there are conflicts now. I have opened a new merge request with only the minimum changes required to fix the issue. Closing this request here. See #710

**Pull request closed without merging**
