### PR TITLE
Add missing type definitions + rename sortFn

### PR DESCRIPTION
**Pull request by jshjohnson**
## Description

- Update types file
- Utilised type defs throughout
- Minor refactoring
- Renames `sortFn` to `sorter` to be consistent with other functions passed via config
- Renames `itemComparer` to `valueComparer` to be clearer about what the function actually does

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tinovyatkin** [comment]
@jshjohnson can we rename `sortFn` to `sortProvider`? My breaking PR is to introduce `searchProvider` and make it easy to build autocomplete on top of Choices

**Comment by tinovyatkin** [comment]
That's also can be done in a way of deprecation - I mean, undocument old settings now, but still support it until next major.

**Comment by tinovyatkin** [comment]
BTW, my `searchProvider` will be support promises (similar to setChoices), not sure if that makes sense for sorting, but...

**Comment by jshjohnson** [comment]
> BTW, my `searchProvider` will be supporting promises (similar to `setChoices` approach), not sure if that makes sense for sorting, but...

Hmm, hard to say without seeing your implementation. Do you mind if I keep this as is for the time being and if we think we need to update it after your search PR, we can?

**Pull request merged**
