### PR TITLE
[MAJOR] Remove `.ajax` and  allow async function for `.setChoices`

### PR DESCRIPTION
**Pull request by tinovyatkin**
Removes `.ajax` method and introduces similar functionality by extending `.setChoices`

## Description

Remove `.ajax` method due to bad name (it's not immediately clear what it does, and soon probably nobody will understand acronym, as I didn't remembered that AJAX stands for **A**synchronous **J**avascript **A**nd **X**ML 😳) and outdated functionality concept.

Introduces abiltiy to pass a callback or async function as first parameter to `.setChoices` to provide similar functionality for today' `Promise` world.

## Motivation and Context

Almost all modern day fetching APIs are Promises based (all your examples except one are), while we are providing _callback_ 😏 way to do that.

This also removes `fetchFromObject` helper function and delegates to consumer to do complete data transformation (`fetchFromObject` handles just one use case, without arrays, etc, and complete solution will require to introduce a huge dependency - so, it's better to let a consumer do whole transformation).

NOTE: This PR is not adding direct dependency on `Promise` implementation in Browser, so, not adding `Promise` to required polyfills.

## How Has This Been Tested?

Refactored existing test and introduced new one.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tinovyatkin** [comment]
Just waiting for #700 to merge and rebase to remove that's code from here.

**Comment by tinovyatkin** [comment]
This also closes #604

**Comment by tinovyatkin** [comment]
Also closes  #626

**Comment by jshjohnson** [comment]
This is much cleaner - thanks!

**Pull request merged**
