### PR TITLE
Groups handling

### PR DESCRIPTION
**Pull request by froggiefab**
Hi,

This PR aims to add groups support on "_ajaxCallback".
I also added two parameters to "_addGroup" defaulted to "value" and "label" to preserve customized properties names.

Thanks.

### CODE REVIEW

**Comment by jshjohnson** [comment]
Thanks - could you provide an example config please :)

**Comment by froggiefab** [comment]
I didn't provide one because it's not in the configuration object :)

The problem occured if the data received during an Ajax request where, for example, of this form :
```json
[
	{
		"label": "France",
		"choices": [
			{ "libelle": "Paris", "code": "PAR"},
			{ "libelle": "Nantes", "code": "NTE"},
			{ "libelle": "Nice", "code": "NCE"},
			{ "libelle": "Bordeaux", "code": "BOD"}
		]
	}
]
```
The callback passed when running "ajax" method :
```javascript
formControl.multiselect.ajax((callback) => {
     ...
     if (request.readyState === 4) {
          status = request.status;
               if (status === 200) {
                    data = JSON.parse(request.responseText);
                    callback(data, 'code', 'libelle', true);
               }
     }
     request.send();
     ...
});
```
The callback was only able to create choices so I added a "_addGroup" call.
But the  "_addGroup" method was always looking for "value" and "label" properties, ignoring the attributes 'code' and 'libelle' passed to the callback so I added necessary parameters.

**Comment by jshjohnson** [comment]
Hey, what is the fourth argument for in your example?

```callback(data, 'code', 'libelle', true);```

Thanks

**Comment by froggiefab** [comment]
A mistake in my code :)

Thanks for noticing.

**Comment by jshjohnson** [comment]
Okay, thanks! :D

**Pull request merged**
