### PR TITLE
Adding a placeholder element for single select dropdown support.

### PR DESCRIPTION
**Pull request by travist**
This pull request provides a pseudo-placeholder for single dropdown selects.

Placeholder

### CODE REVIEW

**Comment by jshjohnson** [comment]
Hey @travist - I'm a bit confused as to what this is resolving :) Could you explain please?

**Comment by travist** [comment]
We use this library for the Form.io javascript renderer @ https://github.com/formio/formio.js. We need to have placeholders be consistent between multiple selects and single select dropdowns and also show consistently across different field types. The way this library deals with placeholders from a technical perspective, where it adds the placeholder property to the select dropdown, is correct, but the display of the dropdown does not show the placeholder. Here is a before and after of our renderer without this fix and with this fix.

**Without Fix** - https://jsfiddle.net/r5Lcw9uq/

**With Fix** - https://jsfiddle.net/ua6zbLvk/

This makes placeholders consistent with Choices.js.  It may be possible I am implementing it wrong, but I have played with every combination of the placeholder settings and could not get it to work like the "fixed" jsfiddle above without this change.

**Comment by jshjohnson** [comment]
Hmm I think this could be achieved by simply adding a placeholder option though, no?

See the default example for a single select [here](https://joshuajohnson.co.uk/Choices/) :)

**Comment by jshjohnson** [comment]
Closing due to inactivity

**Pull request closed without merging**
