### PR TITLE
Fix focus problems

### LINKED ISSUE #8: Bug : select-one is not focusable with Tab key
Because `this.input` is hidden.

Dirty solution : https://github.com/chymz/Choices/commit/e8a5158db74c610575de768d65e7c96192015b42

### PR DESCRIPTION
**Pull request by chymz**
Try to fix #8

### CODE REVIEW

**Comment by chymz** [comment]
Oups i forgot a file :)

**Comment by chymz** [comment]
Fix : onBlur, hide dropdown if search is disabled

**Comment by chymz** [comment]
Seems good now

**Comment by jshjohnson** [comment]
Thanks for this!! I'll test it tomorrow as I'm away from my computer at the moment.

**Pull request merged**
