### PR TITLE
use result.id instead of the index in all places that do that

### PR DESCRIPTION
**Pull request by mike-robertson**

### CODE REVIEW

**Comment by mike-robertson** [comment]
fixes issue #104

**Comment by jshjohnson** [comment]
Looks good! Are you able to put an error in if no group ID is passed?

**Comment by mike-robertson** [comment]
Would you prefer that over generating a uuid (using something like this https://www.npmjs.com/package/uuid)

**Comment by mike-robertson** [comment]
I just threw an error stating that group id is required if it is missing. If you would rather do the UUIDs, it should be pretty simple to implement that instead.

**Comment by jshjohnson** [comment]
I tweaked this slightly to avoid repetition - so if a null ID is passed to `_addGroup`, we generate a unique one.

Thanks for this! 💯

**Pull request merged**
