### PR TITLE
Added resetScrollPosition option

### PR DESCRIPTION
**Pull request by paullaros**
This option allows you to disable the scroll position reset. Very helpful is you have a lot of items in a multiple select-element.

### CODE REVIEW

**Comment by jshjohnson** [comment]
Thanks! Would you mind updating the read me with a brief description of what this config option does please?

**Comment by paullaros** [comment]
:+1:

**Comment by jshjohnson** [comment]
👌🏻

**Comment by SeyamMs** [comment]
😘

**Pull request merged**
