### PR TITLE
Added custom properties to options

### LINKED ISSUE #293: Adding customProperties to choices through markup
Is it possible to add customProperties to choices for select-multiple through markup?
Like through data properties or something?

### PR DESCRIPTION
**Pull request by julian-kuroiwa**
## Description
Added custom properties to the Choices options
This Close #293.

## Motivation and Context
It was required to solve a problem that i was having search. Now when i search for words that i have on custom properties it shows as an option.

## How Has This Been Tested?
Tested on local environment.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by julian-kuroiwa** [comment]
@jshjohnson Ok, I closed the old one and opened this new one. With all updates. it would sweet if you can take a look on this one. 😄

**Comment by jshjohnson** [comment]
Thanks 🎉

**Comment by powerbuoy** [comment]
I'm not sure what I might be doing wrong, but I can't get this to work.

I've got a multiple select with options;

`<select multiple><option data-custom-properties="test" value="1">One</option></select>`

And I'm trying to access my `customProperties` inside the `callbackOnCreateTemplates()->choice()` function but `data.customProperties` is `null` in there.

**Comment by powerbuoy** [comment]
Nevermind, I was using the CDN-version and it wasn't up to date.

**Pull request merged**
