### PR TITLE
Remove need for placeholder "option element" for select one

### PR DESCRIPTION
**Pull request by brennemankyle**
Continuation of this pull request, but now on the develop branch (instead of master) https://github.com/jshjohnson/Choices/pull/269

Features:
- Remove need for placeholder "option element" for select one
- Allow not showing itemSelectText
- Allow removing all items with setValue(null)

### CODE REVIEW

**Comment by brennemankyle** [comment]
Not sure what is wrong with the unit tests... Seems like the error is happening before it calls the tests and files in chai...
@jshjohnson thoughts?

**Comment by brennemankyle** [comment]
ok figured out what I needed, should have tests passing soonish

**Comment by brennemankyle** [comment]
Perfect they are working, I should add some unit tests to make sure these features stay working...

**Comment by brennemankyle** [comment]
Ready for review and merge!

**Comment by brennemankyle** [comment]
@jshjohnson do you actually want to merge this?

**Comment by jshjohnson** [comment]
@brennemankyle conflicts need to be resolved first

**Comment by jshjohnson** [comment]
Closing due to inactivity + amount of conflicts

**Pull request closed without merging**
