### PR TITLE
Remove travis

### PR DESCRIPTION
**Pull request by jshjohnson**
testing

### CODE REVIEW

**Comment by tinovyatkin** [comment]
If you remove versions from index file you also may greatly simplify `postversion` script - keeping just `git commit --atomic` command

**Comment by tinovyatkin** [comment]
@jshjohnson sorry, I mean keep the full command `git push --no-verify --atomic` 😉 - `--no-verify` here keeps husky to retest everything due to `prepush` hook.

**Comment by tinovyatkin** [comment]
You also don't need to install separated babel plugins as `@babel/preset-env` have them all included

**Comment by jshjohnson** [comment]
> You also don't need to install separated babel plugins as `@babel/preset-env` have them all included

@tinovyatkin Is there somewhere that lists what plugins are included with preset-env? Can't find it here: https://babeljs.io/docs/en/babel-preset-env

**Comment by tinovyatkin** [comment]
> @tinovyatkin Is there somewhere that lists which plugins are included with preset-env? Can't find it here: https://babeljs.io/docs/en/babel-preset-env

You may check `dependencies` field at https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json

**Comment by jshjohnson** [comment]
Remove the explicit plugins breaks tests - I suspect i'll need to update the babelrc options. Will do that in another PR 👍

**Comment by tinovyatkin** [comment]
It's Cypress > 3.3 that break the test, I've mentioned it in original PR.

**Comment by jshjohnson** [comment]
🤦‍♂

**Comment by tinovyatkin** [comment]
🎉

**Comment by tinovyatkin** [comment]
You may want to setup Cypress to GitHub integration in this PR too.

**Pull request merged**
