### PR TITLE
Added two config options: shouldSortItems and renderSelectedChoices

### PR DESCRIPTION
**Pull request by maximmig**

### CODE REVIEW

**Comment by jshjohnson** [comment]
Hey @maximmig,

The `shouldSortItems` option is working as expected however the `renderSelectedChoices` option appears to hide all choices in the dropdown - is this intentional? To replicate, change the default value to `false`.

Thanks

**Comment by maximmig** [comment]
OMG, definitely not 😞 I pushed a fix for this and two tests as well, thanks!

**Comment by jshjohnson** [comment]
Thanks!

**Comment by maximmig** [comment]
You're welcome, Josh, more to come! 😄

**Pull request merged**
